#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobile.Resource", IsApplication=true)]

namespace Mobile
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int button_background = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int button_outline_background = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int edit_text_background = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int gradient_background = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int ic_correct = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int ic_incorrect = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int option_background_normal = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int option_background_selected = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int quiz_logo = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int result_background = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int splash_screen = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int averageScoreTextView = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int bestScoreTextView = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int browseQuizzesButton = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int correctOptionLayout = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int correctOptionTextView = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int dateTextView = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int descriptionTextView = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int doneButton = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int emailEditText = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int emptyAttemptsTextView = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int emptyTextView = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int headerLayout = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int loadingProgressBar = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int loginButton = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int navigationLayout = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int nextButton = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int optionsRadioGroup = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int passwordEditText = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int previousButton = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int progressBar = 2130903059;
			
			// aapt resource value: 0x7F030015
			public const int questionCounterTextView = 2130903061;
			
			// aapt resource value: 0x7F030014
			public const int questionCountTextView = 2130903060;
			
			// aapt resource value: 0x7F030016
			public const int questionNumberTextView = 2130903062;
			
			// aapt resource value: 0x7F030019
			public const int questionsRecyclerView = 2130903065;
			
			// aapt resource value: 0x7F030017
			public const int questionTextView = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int questionViewPager = 2130903064;
			
			// aapt resource value: 0x7F03001A
			public const int quizListView = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int quizTitleTextView = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int quizzesTakenTextView = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int recentAttemptsRecyclerView = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int scoreTextView = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int selectedOptionTextView = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int startQuizButton = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int statusImageView = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int timeLimitTextView = 2130903074;
			
			// aapt resource value: 0x7F030024
			public const int timerTextView = 2130903076;
			
			// aapt resource value: 0x7F030023
			public const int timeTextView = 2130903075;
			
			// aapt resource value: 0x7F030025
			public const int titleTextView = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int userNameTextView = 2130903078;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_dashboard = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int activity_quiz_detail = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int activity_quiz_list = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int activity_quiz_result = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int activity_take_quiz = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int layout_attempt_item = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int layout_question_item = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int layout_question_result_item = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int SplashTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F080000
			public const int network_security_config = 2131230720;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
